const steps=[
 {short:'Verbrauch',q:'Wie hoch ist Ihr jährlicher Stromverbrauch?',hint:'Damit erkennen wir, welche Speichergrößen und Einsparhebel grundsätzlich relevant sein können.',answers:['Unter 100.000 kWh','100.000 – 250.000 kWh','250.000 – 500.000 kWh','500.000 – 1.000.000 kWh','1.000.000 – 2.500.000 kWh','Über 2.500.000 kWh']},
 {short:'Lastprofil',q:'Was treibt Ihre Energiekosten aktuell besonders?',hint:'Wählen Sie den Punkt, der Ihren Betrieb am besten beschreibt.',answers:['Hohe Lastspitzen / Leistungspreise','Hoher Stromverbrauch insgesamt','PV-Überschüsse bleiben ungenutzt','Neue Ladeinfrastruktur ist geplant','Schwankende Strompreise','Noch nicht eindeutig']},
 {short:'PV',q:'Wie ist Ihr Unternehmen bei Photovoltaik aufgestellt?',hint:'Eine PV-Anlage ist keine Voraussetzung, eröffnet aber zusätzliche Nutzungsmöglichkeiten.',answers:['PV-Anlage ist vorhanden','PV-Anlage ist konkret geplant','PV-Anlage wird geprüft','Keine PV-Anlage geplant']},
 {short:'Ziel',q:'Welches Ergebnis ist für Sie am wichtigsten?',hint:'So priorisieren wir die wirtschaftlich relevanteste Anwendung.',answers:['Lastspitzen und Netzentgelte reduzieren','PV-Eigenverbrauch maximieren','Stromkosten planbarer machen','Ladeinfrastruktur integrieren','Versorgungssicherheit erhöhen','Mehrere Ziele kombinieren']},
 {short:'Branche',q:'Wo soll das Energiesystem eingesetzt werden?',hint:'Branche und Betriebsweise beeinflussen Lastprofil, Systemauslegung und Umsetzung.',answers:['Produktion / Industrie','Logistik / Lager','Handel / Gewerbe','Hotel / Gastronomie','Immobilie / Quartier','Andere Anwendung']},
 {short:'Zeitraum',q:'Wann möchten Sie Ihre Energiekosten aktiv optimieren?',hint:'Je konkreter der Zeitrahmen, desto gezielter können wir den nächsten Schritt einordnen.',answers:['Innerhalb von 3 Monaten','In 3 bis 6 Monaten','In 6 bis 12 Monaten','Später als 12 Monate','Zunächst Potenzial verstehen']},
 {short:'Rolle',q:'Welche Rolle haben Sie bei der Entscheidung?',hint:'Damit das anschließende Gespräch auf der richtigen Ebene stattfindet.',answers:['Geschäftsführung / Inhaber','Technische Leitung / Energiemanagement','Einkauf / Finanzen','Projektverantwortung','Beratung / Planung','Andere Rolle']},
 {short:'Kontakt',q:'Wohin dürfen wir Ihre persönliche Ersteinschätzung senden?',hint:'Ein Commeo-Experte prüft Ihre Angaben und meldet sich mit einer konkreten Einordnung.',form:true}
];
let current=0;const data={};const progress=document.querySelector('#progress'),q=document.querySelector('#question'),hint=document.querySelector('#hint'),answers=document.querySelector('#answers'),fields=document.querySelector('#formFields'),next=document.querySelector('#next'),back=document.querySelector('#back'),label=document.querySelector('#stepLabel');
progress.style.setProperty('--steps',steps.length);
function validateForm(){const required=[...fields.querySelectorAll('input[required]')];const email=fields.querySelector('input[name="email"]');data[current]=required.every(x=>x.type==='checkbox'?x.checked:x.value.trim())&&(!email||email.validity.valid);next.disabled=!data[current]}
function render(){const s=steps[current];progress.innerHTML=steps.map((x,i)=>`<div class="prog ${i<=current?'active':''}"><i>${i+1}</i><span>${x.short}</span></div>`).join('');label.textContent=`Schritt ${current+1} von ${steps.length}`;q.textContent=s.q;hint.textContent=s.hint;answers.innerHTML='';fields.innerHTML='';back.style.visibility=current?'visible':'hidden';next.textContent=current===steps.length-1?'Ersteinschätzung anfordern →':'Weiter →';next.disabled=!data[current];if(s.form){fields.innerHTML=`<div class="field-row"><label>Vorname<input name="first" autocomplete="given-name" required></label><label>Nachname<input name="last" autocomplete="family-name" required></label></div><label>Unternehmen<input name="company" autocomplete="organization" required></label><div class="field-row"><label>Geschäftliche E-Mail<input name="email" type="email" autocomplete="email" required></label><label>Telefon für Rückfragen<input name="phone" type="tel" autocomplete="tel" required></label></div><div class="field-row"><label>PLZ des Standorts<input name="zip" inputmode="numeric" autocomplete="postal-code" required></label><label>Website <span>(optional)</span><input name="website" type="url" placeholder="https://"></label></div><label class="consent"><input name="consent" type="checkbox" required><span>Ich stimme zu, dass Commeo meine Angaben zur Bearbeitung der Potenzialanalyse und zur persönlichen Kontaktaufnahme verwendet. Hinweise zum Datenschutz habe ich zur Kenntnis genommen.</span></label>`;fields.querySelectorAll('input').forEach(i=>{i.addEventListener('input',validateForm);i.addEventListener('change',validateForm)});}else{s.answers.forEach(a=>{const b=document.createElement('button');b.className='answer'+(data[current]===a?' selected':'');b.textContent=a;b.onclick=()=>{data[current]=a;render()};answers.appendChild(b)})}}
next.onclick=()=>{if(current<steps.length-1){current++;render()}else{document.querySelector('.quiz-card').innerHTML=`<div class="success"><span>✓</span><p class="section-label">Anfrage erfolgreich qualifiziert</p><h1>Vielen Dank für Ihre Angaben.</h1><p>Ein Commeo-Experte prüft jetzt, welche Einsparhebel und Systemrichtungen zu Ihrem Unternehmen passen. Sie erhalten anschließend eine persönliche Rückmeldung.</p><a class="btn" href="/">Zurück zur Startseite →</a></div>`}};back.onclick=()=>{if(current){current--;render()}};render();
