const steps=[
 {short:'Verbrauch',q:'Wie hoch ist Ihr jährlicher Stromverbrauch?',hint:'Eine grobe Einschätzung reicht für den ersten Check.',answers:['Unter 100.000 kWh','100.000 – 250.000 kWh','250.000 – 500.000 kWh','500.000 – 1.000.000 kWh','1.000.000 – 2.500.000 kWh','Über 2.500.000 kWh']},
 {short:'Lastspitzen',q:'Wie relevant sind Lastspitzen für Ihren Betrieb?',hint:'Zum Beispiel durch Maschinen, Kühlung oder Ladeinfrastruktur.',answers:['Sehr relevant','Teilweise relevant','Noch unklar']},
 {short:'PV-Anlage',q:'Nutzen oder planen Sie eine PV-Anlage?',hint:'Mehrfachnutzung des Speichers kann die Wirtschaftlichkeit erhöhen.',answers:['Ja, bereits vorhanden','Ja, in Planung','Nein / noch unklar']},
 {short:'Ziel',q:'Was möchten Sie vorrangig erreichen?',hint:'Wählen Sie den wichtigsten Hebel für Ihr Unternehmen.',answers:['Lastspitzen reduzieren','PV-Eigenverbrauch erhöhen','Strom flexibel einkaufen','Ladeinfrastruktur integrieren','Versorgung absichern']},
 {short:'Unternehmen',q:'Wo soll das System eingesetzt werden?',hint:'Damit wir die mögliche Lösung besser einordnen können.',answers:['Produktion / Industrie','Logistik / Lager','Handel / Gewerbe','Hotel / Gastronomie','Immobilie / Quartier','Andere Anwendung']},
 {short:'Kontakt',q:'Wohin dürfen wir Ihre Potenzial-Einordnung senden?',hint:'Ein Commeo-Experte meldet sich persönlich und unverbindlich.',form:true}
];
let current=0;const data={};const progress=document.querySelector('#progress'),q=document.querySelector('#question'),hint=document.querySelector('#hint'),answers=document.querySelector('#answers'),fields=document.querySelector('#formFields'),next=document.querySelector('#next'),back=document.querySelector('#back'),label=document.querySelector('#stepLabel');
function render(){const s=steps[current];progress.innerHTML=steps.map((x,i)=>`<div class="prog ${i<=current?'active':''}"><i>${i+1}</i><span>${x.short}</span></div>`).join('');label.textContent=`Schritt ${current+1} von ${steps.length}`;q.textContent=s.q;hint.textContent=s.hint;answers.innerHTML='';fields.innerHTML='';back.style.visibility=current?'visible':'hidden';next.textContent=current===steps.length-1?'Potenzial-Check absenden →':'Weiter →';next.disabled=!data[current];if(s.form){fields.innerHTML=`<div class="field-row"><label>Vorname<input name="first" autocomplete="given-name" required></label><label>Nachname<input name="last" autocomplete="family-name" required></label></div><label>Unternehmen<input name="company" autocomplete="organization" required></label><div class="field-row"><label>E-Mail<input name="email" type="email" autocomplete="email" required></label><label>Telefon<input name="phone" type="tel" autocomplete="tel"></label></div>`;fields.querySelectorAll('input').forEach(i=>i.addEventListener('input',()=>{data[current]=[...fields.querySelectorAll('input[required]')].every(x=>x.value.trim());next.disabled=!data[current]}));}else{s.answers.forEach(a=>{const b=document.createElement('button');b.className='answer'+(data[current]===a?' selected':'');b.textContent=a;b.onclick=()=>{data[current]=a;render()};answers.appendChild(b)})}}
next.onclick=()=>{if(current<steps.length-1){current++;render()}else{document.querySelector('.quiz-card').innerHTML=`<div class="success"><span>✓</span><p class="section-label">Vielen Dank</p><h1>Ihre Angaben sind bei uns angekommen.</h1><p>Ein Commeo-Experte prüft Ihre Angaben und meldet sich persönlich bei Ihnen.</p><a class="btn" href="/">Zurück zur Startseite →</a></div>`}};back.onclick=()=>{if(current){current--;render()}};render();
